sudo: false
branches:
  only:
    - master
language: python

matrix:
  include:
    - os: linux
      dist: precise
      python: 2.7
    - os: linux
      dist: precise
      python: 3.4
    - os: osx
      osx_image: xcode8.3

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - clang-format-3.8
install:
  - ./scripts/travis/install.sh
script:
  - ./scripts/travis/build.sh
